### ISSUE TITLE
Require version number as part of identifier for definitions

### ISSUE THREAD

**Issue by sy238-unikent** [unikent/astro#166]
The code is not consistent over when -v{version} should be appended to the end of definition identifiers and when not to.

Explicitly declaring the version numbers everywhere is required.

**Comment by sy238-unikent** [comment]
### Version Number Used

- js/index.js and js/layouts.js do declare the ids of layouts and blocks using {name}-v{version}.
- blocks stored in the Editor (classes/Definitions.js) - are indexed by {name}-v{version}
- API - blocks stored in database have the name AND version stored for each block, but as different attributes,

### Version Number Not Used

- regions stored in the Editor (classes/Definitions.js) - are indexed by name, not version
- blocks listed in sections in region definitions - but version IS required in schema
- regions listed in layout definitions - version not required in schema, but maybe should be?
- API code to locate block definitions expects a name without version, plus optional version

**Comment by theninja** [comment]
Yup, this should never be hard-coded and the API should return blocks etc with the name and version number as the identifier.

The `getType` method in the Definition class is a dumb bit of code that creates these identifiers, given a definition.

**Comment by sy238-unikent** [comment]
I guess this will also require us to store block data with versions as part of the region name, e.g.
```javascript
blocks = {
   'main-v1': [ {section...} ],
   'sidebar-v1': [ {section...} ] 
}
```

**Comment by sy238-unikent** [comment]
WIP branch: https://github.com/unikent/astro/tree/fix/require-version-number-in-definition-ids

mostly done (hopefully!) in the API, plus tests updated.

Now need to fix the editor.

It may be that storing the definition_id ( {name}-v{version} ) rather than name and version separately makes more sense... but that needs more investigation.

**Comment by sy238-unikent** [comment]
These changes mean that definition name and version must be used together to specify a definition.

Specifying a definition by name only is invalid.

The purpose of different versions is to specify breaking changes in definitions, and to allow us to in the future create tooling to assist in upgrading pages from old versions of blocks, regions or layouts to newer versions in an as sane-as-possible manner.
