### ISSUE TITLE
Why does DefinitionBroker depend on BlockDefinition rather BaseDefinition?

### ISSUE THREAD

**Issue by jna-unikent** [unikent/astro#169]
See: https://github.com/unikent/astro/blob/develop/app/Validation/Brokers/DefinitionBroker.php#L16

**Comment by theninja** [comment]
As it currently stands that's more of a `BlockDefinitionBroker`, since it deals with validation rules specific to blocks, so perhaps it's more a case of the class being awkwardly named. It's possible this was intended to be more generic, not sure, but right now it isn't.
