### ISSUE TITLE
Remove unused PersistRequest and other request classes from API

### ISSUE THREAD

**Issue by jna-unikent** [unikent/astro#170]
Remove PersistRequest https://github.com/unikent/astro/blob/develop/app/Http/Requests/Api/v1/Page/PersistRequest.php

This is a formRequest which appears is no longer used (because we're using http calls to the api rather than forms)

We should also remove:
- the tests for PersistRequest - https://github.com/unikent/astro/blob/develop/tests/Unit/Http/Requests/Api/v1/Page/PersistRequestTest.php

- the reference to this within the main readme.md
- Blockbroker->getRegionConstraintRules (which is only used in the PersistRequestTest) - https://github.com/unikent/astro/blob/develop/app/Validation/Brokers/BlockBroker.php#L92

**Comment by theninja** [comment]
The naming is a bit deceptive, `FormRequest` is used even for non forms in Laravel.
This was probably just something @samyapp never got around to removing when he refactored the API. It looks like almost all the code was moved across to [UpdateContent.php](https://github.com/unikent/astro/blob/c1cedb41dbcb0c5085a6758b20bf964bbb6afde7/app/Models/APICommands/UpdateContent.php). Which might mean we can copy some of the tests over too, unless that's already been done, as the code is basically the same.

**Comment by cfc7-unikent** [comment]
done!
