### ISSUE TITLE
Form fields in blocks in the editor (especially submit buttons) should be disabled.

### ISSUE THREAD

**Issue by sy238-unikent** [unikent/astro#198]
Similar to the way that we deactivate all links inside the edited content.

**Comment by cfc7-unikent** [comment]
Pull request at https://github.com/unikent/astro/pull/216

**Comment by cfc7-unikent** [comment]
@sy238-unikent @gnozu 
Ready to merge - changes are in astro and cms-prototype-blocks 

https://github.com/unikent/cms-prototype-blocks/pull/94
https://github.com/unikent/cms-prototype-blocks/pull/94

**Comment by cfc7-unikent** [comment]
For future reference: 
Main issue I had with this was that my original approach was to avoid having to change cms-prototype-blocks and instead reach into the layout components via the preview component in astro.

The way that preview.vue dynamically loads up the comonents for the layouts meant that they were not actually mounted when preview.vue was mounted. This was unexpected and too some quality investigation by @theninja to find what was going wrong.

Adding a baselayout and then just having the cms-prototype-blocks extend that ended up being a much quicker and cleaner way of doing this.

**Comment by samyapp** [comment]
An unintended side-effect is that the add block button in our empty section component no longer works.

I'm going to implement a quick-fix which doesn't disable buttons if they have the class "el-button".
